### ISSUE TITLE
Subscription callback randomly stops to work, but running does not freeze

### ISSUE THREAD

**Issue by cosmolabs-ru** [fizista/micropython-umqtt.robust2#14]
**Describe the bug**
I run code similar to [example_sub_robust.py](https://github.com/fizista/micropython-umqtt.robust2/blob/master/example_sub_robust.py) (only filled in my wifi & mqtt creds). Also tested it in my app, which is a simple relay on/off switch. In my app, the main `while(1)` loop is copy-pasted from the above example.  
The code starts up fine, but after a random period of time (from several minutes to 8-10 hours) subcription callback won't trigger upon a subscribed topic update. Meanwhile, the main loop keeps running and connection is not dropped. I determined this by placing debug prints in sub callback and in main loop. 
Using watchdog makes no sense in main loop, because it keeps running. Checking of `is_conn_issue()` in the main loop deos not fire.
Note: the mqtt broker is not in the LAN, but is in the Internet. 

**To Reproduce**
Run example above
Periodically publish to a topic subscribed by device
Look if device reacts

**Applicable workaround**
I added a separate "alive" topic and subscribed to it. I publish a random value into it at each main loop cycle. (BTW, this increases time to reproduce the bug). At every publish, sub callback triggers and feeds the watchdog. When bug reproduces, sub callback does not trigger and then watchdog resets the MCU. 

**Details (please complete the following information):**
 - Device board: ESP-WROOM-32D, ESP-12F (8266-based)
 - Micropython version: 1.19, 1.21
 - Library version: master branch as of 12 Dec 2023

**Comment by fizista** [comment]
Is your client publishing something to the server while waiting? A "ping" once every half of the time declared in keepalive is enough.

**Comment by cosmolabs-ru** [comment]
> Is your client publishing something to the server while waiting? A "ping" once every half of the time declared in keepalive is enough.

 Thx, will try and report result

**Comment by cosmolabs-ru** [comment]
> A "ping" once every half of the time declared in keepalive is enough

This solution works, thanks. 
My mistake I didn't specify keepalive time at `MQTTClient` class instantiation. 
But the root cause of unstable work was severely degraded performance of my home router. It only yielded 2 Mbps through 2.4GHz. I discovered that by a coincidence. After installing a fresh Xiaomi router, reliability issues are gone.
