### ISSUE TITLE
AttributeError: 'MQTTClient' object has no attribute 'is_conn_issue'

### ISSUE THREAD

**Issue by gurkancekic** [fizista/micropython-umqtt.robust2#5]
![image](https://user-images.githubusercontent.com/19389584/100552311-83588880-3297-11eb-8acd-14991d3c3af8.png)
  File "<stdin>", line 95, in <module>
AttributeError: 'MQTTClient' object has no attribute 'is_conn_issue'

**Comment by fizista** [comment]
I would look for a problem in importing class. I do not see what you are importing or how you are initiating a class.
