### ISSUE TITLE
randomly stuck at check_msg()

### ISSUE THREAD

**Issue by garudaonekh** [fizista/micropython-umqtt.robust2#8]
Hi,
This library and simple2 sometimes stuck at check_msg() and never return from it. I think it's due to Socket timeout or connection issue. This happen now and then and it happen more often when the connection is unstable.

This is a serious issue. Is there any workaround?

Thanks;

**Comment by fizista** [comment]
If you can find the exact place in the code where it freezes, maybe I can improve it.

I've also noticed that it sometimes crashes in some way. It happened not only under MicroPython, but also under code written in ardiuno.

**Comment by garudaonekh** [comment]
It's hard to trace as it get stuck and never return and may happen after a few hours or so or can be day. and the watchdog kick in and reboot.

I think the workaround will be to force socket class to return or kill its process but I don't see any function to do that.

**Comment by Joris140404** [comment]
I have the same issue, it gets frozen and the only fix I found is rebooting.

**Comment by garudaonekh** [comment]
> I have the same issue, it gets frozen and the only fix I found is rebooting.

Do you have any clue or the pattern how this happen?

**Comment by garudaonekh** [comment]
> I am using umqttsimple which seems to be an ancestor of umqtt-robust. I was having odd crashes until yesterday. ....
> 
> To find the problem I ran the code from Thonny with lots of debug prints, Wireshark to check the traffic and "tailing" the MQTT logfile. The problem was that, when I was developing additional nodes for my network of ESP32's, I had one node with the same client ID as a node that was in-service.
> 
> When MQTT detects a duplicate client ID, by design it disconnects the first client. This means immediately closing the socket. In umqttsimple this generated an OSError(-1) and the program exited right there.
> 
> It may be the problem is really with the micropython socket code or the ESP32 FreeRTOS which doesn't handle the sudden close properly. I was in a hurry so I changed the code in umqttsimple to "fix" this.
> 
> The problem was hard to find as it appeared to be random and I only noticed the dead nodes when the MQTT data has stopped.
> 
> It may be that this is not the problem in which case nothing has been lost other than the time to read this.

The problem for me is that the check_msg() never return. It get stuck in the socket class which make the device hang until watchdog reboot the device.

Yes, I also see OSError(-1) in the code for example, when the MQTT broker is down or connection issue.

**Comment by sahil06habile** [comment]
You

> > I am using umqttsimple which seems to be an ancestor of umqtt-robust. I was having odd crashes until yesterday. ....
> > To find the problem I ran the code from Thonny with lots of debug prints, Wireshark to check the traffic and "tailing" the MQTT logfile. The problem was that, when I was developing additional nodes for my network of ESP32's, I had one node with the same client ID as a node that was in-service.
> > When MQTT detects a duplicate client ID, by design it disconnects the first client. This means immediately closing the socket. In umqttsimple this generated an OSError(-1) and the program exited right there.
> > It may be the problem is really with the micropython socket code or the ESP32 FreeRTOS which doesn't handle the sudden close properly. I was in a hurry so I changed the code in umqttsimple to "fix" this.
> > The problem was hard to find as it appeared to be random and I only noticed the dead nodes when the MQTT data has stopped.
> > It may be that this is not the problem in which case nothing has been lost other than the time to read this.
> 
> The problem for me is that the check_msg() never return. It get stuck in the socket class which make the device hang until watchdog reboot the device.
> 
> Yes, I also see OSError(-1) in the code for example, when the MQTT broker is down or connection issue.

You found any solution on this ? I'm also facing the same issue with micropython running on esp32 and esp32 randomly stuck on check_msg() when there is a incoming message.

**Comment by garudaonekh** [comment]
> 

No,
my workaround is using watchdog to reset the board if it gets stuck

**Comment by fizista** [comment]
There is a new version of umqtt-simple2=v2.2.0. 

Probably the problems have been fixed in this library, please let us know if they still occur.
